server:
  port: 8060
  tomcat:
    max-http-form-post-size: 8192
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?serverTimezone=GMT&?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Esport.work.entity 